### ISSUE TITLE
using "Down" in the search-bar leads to a core dump on the first use

### ISSUE THREAD

**Issue by apm256** [gauteh/astroid#130]
Steps to reproduce the bug:
1. `rm ~/.config/astroid/searches`
2. launch astroid
3. use `F`, then write a query, and press `Enter`
4. use `F`, then `Down`

Step 4 leads to a core dump.

(Thank you for the saved sarch feature, by the way!)

**Comment by gauteh** [comment]
apm256 writes on mai 11, 2016 10:22:
> Steps to reproduce the bug:
> 1. `rm ~/.config/astroid/searches`
> 2. launch astroid
> 3. use `F`, then write a query, and press `Enter`
> 4. use `F`, then `Down`
> 
> Step 4 leads to a core dump.

I cannot reproduce this.. are you on latest master? Could you send a
stack-trace?

**Comment by apm256** [comment]
The stack trace does not seem very useful:
```
[...]
[debug] (10:37:14): cb: previous history
Erreur de segmentation (core dumped)
```
No crash with `Up`, by the way.

It is only a minor annoyance. Feel free to close this issue if you are not able to reproduce it.

**Comment by gauteh** [comment]
apm256 writes on mai 11, 2016 10:41:
> The stack trace does not seem very useful:
> ```
> [...]
> [debug] (10:37:14): cb: previous history
> Erreur de segmentation (core dumped)
> ```
> No crash with `Up`, by the way.
> 

Must be an error somewhere. I mean: a gdb stacktrace. If you are on
arch:

$ coredumpctl gdb astroid
(gdb) bt

or, directly:
$ gdb --args ./astroid --no

[...] reproduce, and output appears in gdb.

**Comment by apm256** [comment]
Here it is:

```
Thread 1 "astroid" received signal SIGSEGV, Segmentation fault.
0x00007ffff63ad7a0 in Glib::ustring::c_str() const () from /usr/lib/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff63ad7a0 in Glib::ustring::c_str() const () from /usr/lib/libglibmm-2.4.so.1
#1  0x00007ffff7377c6c in Gtk::Entry::set_text(Glib::ustring const&) () from /usr/lib/libgtkmm-3.0.so.1
#2  0x000000000043cc1e in ?? ()
#3  0x00007ffff741289d in ?? () from /usr/lib/libgtkmm-3.0.so.1
#4  0x00007ffff345214c in ?? () from /usr/lib/libgtk-3.so.0
#5  0x00007ffff2990fa5 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff29a3294 in ?? () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff29ab829 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff29ac0bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff3594ecc in ?? () from /usr/lib/libgtk-3.so.0
#10 0x00007ffff35b506b in gtk_window_propagate_key_event () from /usr/lib/libgtk-3.so.0
#11 0x00007ffff35b8acb in ?? () from /usr/lib/libgtk-3.so.0
#12 0x00007ffff740c6e4 in Gtk::Widget::on_key_press_event(_GdkEventKey*) () from /usr/lib/libgtkmm-3.0.so.1
#13 0x00007ffff740ea24 in Gtk::Widget_Class::key_press_event_callback(_GtkWidget*, _GdkEventKey*) ()
   from /usr/lib/libgtkmm-3.0.so.1
#14 0x00007ffff345214c in ?? () from /usr/lib/libgtk-3.so.0
#15 0x00007ffff2990fa5 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff29a359e in ?? () from /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff29ab829 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff29ac0bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff3594ecc in ?? () from /usr/lib/libgtk-3.so.0
#20 0x00007ffff344f5c9 in ?? () from /usr/lib/libgtk-3.so.0
#21 0x00007ffff345134c in gtk_main_do_event () from /usr/lib/libgtk-3.so.0
#22 0x00007ffff2f89625 in ?? () from /usr/lib/libgdk-3.so.0
#23 0x00007ffff2fb6492 in ?? () from /usr/lib/libgdk-3.so.0
#24 0x00007ffff26baf07 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#25 0x00007ffff26bb160 in ?? () from /usr/lib/libglib-2.0.so.0
#26 0x00007ffff26bb20c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#27 0x00007ffff2c80afd in g_application_run () from /usr/lib/libgio-2.0.so.0
#28 0x000000000042538e in ?? ()
#29 0x00007ffff149c710 in __libc_start_main () from /usr/lib/libc.so.6
#30 0x0000000000426d49 in ?? ()
(gdb)
```

**Comment by gauteh** [comment]
Hm - still not able to reproduce it, do you have the latest versions of
gtkmm and glibmm?

**Comment by apm256** [comment]
Very strange: I changed nothing, but now, I can't reproduce the crash either... It was however perfectly deterministic this morning (I tried it twenty times, at least).
I will warn you if I find an explanation.

**Comment by gauteh** [comment]
Ok, please re-open if it happens again.
